services:
  - type: web
    name: puppet
    env: node
    buildCommand: |
      # Install Chromium and its dependencies
      apt-get update
      apt-get install -y chromium chromium-sandbox
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: NODE_ENV
        value: production 