services:
  - type: web
    name: puppet-app
    env: node
    buildCommand: |
      # Build frontend
      cd frontend
      npm install
      npm run build
      cd ..
      # Build backend
      cd backend
      npm install
      npm run build
      cd ..
    startCommand: |
      cd backend
      node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
    disk:
      name: uploads
      mountPath: /opt/render/project/src/backend/uploads
      sizeGB: 1 