services:
  - type: web
    name: puppet
    env: node
    buildCommand: |
      npm install
      npm run build
      apt-get update
      apt-get install -y chromium
    startCommand: npm start
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true" 