services:
  # Combined Service
  - type: web
    name: puppet-app
    env: node
    buildCommand: |
      # Install and build backend
      cd backend
      npm ci
      npm run build
      cd ..

      # Install and build frontend
      cd frontend
      npm ci
      npm run build
      cd ..
    startCommand: |
      cd backend && npm start &
      cd frontend && npm run preview
    envVars:
      # Backend Environment Variables
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: "https://puppet-app.onrender.com"
      - key: SCRAPER_WORKER_URL
        value: "https://linkedin-scraper.sigmasigma.workers.dev"
      # Frontend Environment Variables
      - key: VITE_GROQ_API_KEY
        sync: false
      - key: VITE_API_URL
        value: "https://puppet-app.onrender.com/api" 