services:
  # Backend Service
  - type: web
    name: puppet-backend
    env: node
    rootDir: backend
    buildCommand: |
      npm ci
      npm run build
      mkdir -p dist
      cp package*.json dist/
      cd dist && npm ci --production
    startCommand: cd dist && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SCRAPER_WORKER_URL
        value: "https://linkedin-scraper.sigmasigma.workers.dev"

  # Frontend Service
  - type: web
    name: puppet-frontend
    env: node
    rootDir: frontend
    buildCommand: npm ci && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_GROQ_API_KEY
        sync: false
      - key: VITE_API_URL
        sync: false 